# Site settings
title: "Cyber Security Analyst - Nidhi"
description: "Cyber Security Analyst"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Nidhi Anand"
resume_title:                   "Cyber Security Analyst"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nidhianand7@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9813746272"
resume_contact_address:         "Gurgaon, India"

resume_header_contact_info:     "Gurgaon, India • +91-98137-46272 • nidhianand7@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>7+ years of experience in Cyber Security & Network Management, Interested in securing products that help humans live to their values and potential, exploring the intersection between tech x ethics.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "https://twitter.com/sachdevageetesh"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
   resume_linkedin_url:          "www.linkedin.com/in/nidhianand7"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
# resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
